# Generated by Django 3.2.4 on 2021-06-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210630_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
