# Generated by Django 3.2.4 on 2021-06-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
