# Generated by Django 3.2.4 on 2021-07-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210713_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uid',
            new_name='user_id',
        ),
    ]
