# Generated by Django 3.2.4 on 2021-07-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_rename_uid_post_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='title',
        ),
    ]
