# Generated by Django 3.2.4 on 2021-07-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_rename_user_id_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='uid', max_length=100, unique=True),
        ),
    ]
