# Generated by Django 3.2.4 on 2021-07-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='uid',
        ),
    ]
