# Generated by Django 3.2.4 on 2021-07-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_rename_title_post_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reason',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='Reason for report...'),
        ),
    ]
